common: &common
  hosts: <%= ENV['COUCHBASE_HOST'] || 'localhost' %> 
  password: <%= ENV['COUCHBASE_PASSWORD'] %>

development:
  <<: *common
  bucket: <%= ENV['COUCHBASE_BUCKET'] || 'default' %>

test:
  <<: *common
  bucket: engine_app_test

# set these environment variables on your production server
production:
  hosts: <%= ENV['COUCHBASE_HOST'] %>
  bucket: <%= ENV['COUCHBASE_BUCKET'] %>
  password: <%= ENV['COUCHBASE_PASSWORD'] %>
  operation_timeout: 10
  config_total_timeout: 10
